name: Deploy Federal Corporations Search Datasette

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Download and process data
      run: |
        mkdir -p OPEN_DATA_SPLIT
        wget -O OPEN_DATA_SPLIT/OPEN_DATA_SPLIT.zip https://ised-isde.canada.ca/cc/lgcy/download/OPEN_DATA_SPLIT.zip
        unzip OPEN_DATA_SPLIT/OPEN_DATA_SPLIT.zip -d OPEN_DATA_SPLIT
        rm OPEN_DATA_SPLIT/OPEN_DATA_SPLIT.zip
        pipenv install
        pipenv run python main.py

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        known_hosts: unnecessary

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USER: root
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${USER}@${HOST}:/var/www/datasette/federal-corporations-search/
        ssh -o StrictHostKeyChecking=no ${USER}@${HOST} \
          'cd /var/www/datasette/federal-corporations-search && pipenv install && chmod +x .digitalocean/run.bash && systemctl restart datasette-federal-corporations-search.service'